FROM python:3.12-slim

RUN mkdir /app

WORKDIR /app

# Set environment variables 
# Prevents Python from writing pyc files to disk
ENV PYTHONDONTWRITEBYTECODE=1
#Prevents Python from buffering stdout and stderr: Log instantly to the console
ENV PYTHONUNBUFFERED=1

# Upgrade pip
RUN pip install --upgrade pip

# Install dependencies
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# COPY Project code
COPY . /app/

# EXPOSE
EXPOSE 8000

# RUN DJANGO Dev Server
CMD ["sh", "-c", "wait-for-db.sh && python manage.py runserver 0.0.0.0:8000"]