[supervisord]
nodaemon=true

[program:gunicorn]
# Command to start your Gunicorn web application
command=gunicorn --bind 0.0.0.0:8000 --workers 3 config.wsgi:application
directory=/app
user=appuser
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:consumer]
# Command to run your consumer.py script
# We use the python binary that was copied from the builder stage
command=/usr/local/bin/python consumer.py 
directory=/app
user=appuser
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0