# Generated by Django 5.2.8 on 2025-11-22 10:00

import django.db.models.deletion
import purchase_requests.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('proforma', models.URLField(blank=True, max_length=500, null=True)),
                ('receipt', models.URLField(blank=True, max_length=500, null=True)),
                ('purchase_order', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('approval_levels', models.JSONField(default=purchase_requests.models.default_approval_levels)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Purchase Request',
                'verbose_name_plural': 'Purchase Requests',
                'db_table': 'purchase_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
