# Generated by Django 5.2.8 on 2025-11-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='proforma',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='purchase_order',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='receipt',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
