# Generated by Django 5.2.8 on 2025-11-22 20:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('approval_level', models.CharField(help_text="The approval level at which this decision was made (e.g., 'approver-level-1', 'approver-level-2')", max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, help_text='Optional comment from the approver', null=True)),
                ('approver', models.ForeignKey(db_column='approver_id', on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to=settings.AUTH_USER_MODEL)),
                ('purchase_request', models.ForeignKey(db_column='purchase_request_id', on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='purchase_requests.purchaserequest')),
            ],
            options={
                'verbose_name': 'Decision',
                'verbose_name_plural': 'Decisions',
                'db_table': 'decisions',
                'ordering': ['-created_at'],
                'unique_together': {('purchase_request', 'approver')},
            },
        ),
    ]
