# Generated by Django 5.2.8 on 2025-11-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_requests', '0002_decision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decision',
            name='decision',
            field=models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject')], max_length=20),
        ),
    ]
