# Generated by Django 5.2.8 on 2025-11-26 20:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_requests', '0003_alter_decision_decision'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderReceiptMismatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purchase_request_id', models.UUIDField()),
                ('result', models.TextField()),
            ],
            options={
                'verbose_name': 'Purchase Order / Receipt Mismatch',
                'verbose_name_plural': 'Purchase Order / Receipt Mismatches',
                'db_table': 'purchase_order_receipt_mismatches',
            },
        ),
        migrations.AlterField(
            model_name='decision',
            name='comment',
            field=models.TextField(blank=True, default='no comment', help_text='Optional comment from the approver'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='decision',
            name='decision',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='description',
            field=models.TextField(blank=True, default='Description'),
            preserve_default=False,
        ),
    ]
