# Generated by Django 5.2.8 on 2025-11-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_requests', '0004_purchaseorderreceiptmismatch_alter_decision_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decision',
            name='comment',
            field=models.TextField(blank=True, default='No comment', help_text='Optional comment from the approver'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='description',
            field=models.TextField(blank=True, default='Description'),
        ),
    ]
