name: Pipeline - Build & Deploy

on:
  push:
    branches: [main]
    paths-ignore:
      - "!*.md"
  workflow_dispatch:

jobs:
  test_build:
    name: "[Prod Depl] Run tests & Build Image"
    uses: ./.github/workflows/test_build.yml
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

  deploy:
    name: "[Prod Depl] Deploye to ACA"
    runs-on: ubuntu-latest
    needs: test_build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login into Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          registryUrl: ericndungutse.docker.io
          containerAppName: procure-to-pay-api
          resourceGroup: procure-to-pay-ist_group
          imageToDeploy: ericndungutse/procure-to-pay-bn:latest
